const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={interests:[],values:[],careers:[],index:0,results:[],profile:{},mode:'guided',returnScreen:'profileScreen'};
const careers={
finance:{name:'财务分析',type:'专业延伸',desc:'用财务和经营数据解释企业发生了什么，并支持预算与经营决策。',work:'整理预算与实际数据、分析收入成本变化、发现经营风险，并把结论解释给业务团队。',skills:'财务基础、Excel、数字敏感度、业务理解与结论表达。',background:'部分高薪岗位看重学历、院校和实习平台；普通院校学生可用证书、建模作品、行业研究和实习成果证明能力。',caution:'需要长期处理数字和细节，进阶还要理解业务，而不只是做账。',reasons:['能利用现有专业课程积累','适合愿意分析和制定规则的人','可以通过案例快速验证数字敏感度'],case:'你是连锁奶茶店的财务分析实习生。A店本月收入10万元，原料3万元、房租2万元、人工3万元；上月收入12万元，三项成本分别为3.2万元、2万元和2.8万元。店长认为“本月仍然盈利，所以经营没有问题”。',questions:['分别计算两个月的利润','指出最值得追问的一项变化及原因','店长的结论是否充分？还需要哪两类信息'],focus:'从有限数据中发现异常，并说明还缺少什么证据。',next:'再比较一家门店的数据',purpose:'验证你是否愿意继续做“比较—追问—解释”这一类财务分析工作，而不是要求你去访谈别人。'},
data:{name:'数据分析',type:'能力迁移',desc:'把杂乱数据转化为可以支持判断的证据。',work:'清洗数据、计算指标、寻找变化、制作图表，并向业务团队解释结论和局限。',skills:'Excel或SQL、指标意识、逻辑分析、数据可视化和沟通表达。',background:'院校背景会影响部分头部岗位筛选，但清晰的数据项目、SQL能力和业务分析作品是重要补充。',caution:'工作不只是“做图”，需要反复检查数据质量，也不能把相关性误当成因果。',reasons:['你选择了分析或学习工具类活动','项目成果便于展示','多数专业可通过小案例验证'],case:'你负责分析一款校园学习App的7日数据：周一至周日新增用户分别为120、130、125、400、150、145、140；次日留存率分别为42%、40%、41%、18%、39%、38%、40%。周四刚好投放了一次校园广告。',questions:['周四的数据与其他天相比有什么异常','仅凭这些数据能否判断广告有效？为什么','为了决定是否继续投放，你还需要哪三项数据'],focus:'识别异常、避免草率归因，并提出需要补充的数据。',next:'把结论整理成一页分析卡',purpose:'验证你是否喜欢把数字变化转化为有边界的业务判断，同时形成第一份可展示的小成果。'},
product:{name:'产品经理',type:'兴趣迁移',desc:'发现用户在具体场景中的问题，判断优先级并推动团队改进产品。',work:'访谈用户、分析使用场景、定义问题、撰写需求并与设计和研发协作验证方案。',skills:'用户洞察、问题定义、逻辑表达、优先级判断和协作推进。',background:'头部岗位可能看重学校和实习经历；具体的问题分析、原型和项目复盘能提供更直接的能力证据。',caution:'不是只负责“想创意”，还要接受约束、处理冲突并为取舍负责。',reasons:['适合喜欢研究问题和协调推进的人','可以利用日常产品完成体验','沟通与分析能力可跨专业迁移'],case:'你每天使用校园App预约自习室。最近三次预约时，你都要先选择校区、楼栋、日期、楼层，再逐个打开房间才能知道是否有座位。高峰期操作到最后才发现全部约满。',questions:['用一句话描述：哪类用户在什么场景遇到了什么困难','判断最核心的问题是步骤多、信息出现太晚，还是其他原因，并说明依据','提出一个最小改进方案，并说明它优先解决什么'],focus:'把模糊抱怨转化为“用户—场景—问题—取舍”。',next:'用同一框架分析另一个真实场景',purpose:'不是要求你必须访谈同学，而是检查你能否稳定地区分表面现象与核心问题。'},
content:{name:'内容运营',type:'兴趣迁移',desc:'围绕目标人群策划内容，并用反馈数据持续优化表达。',work:'研究用户、制定选题、生产内容、运营渠道、观察数据并复盘哪些内容有效。',skills:'用户洞察、选题策划、写作表达、渠道理解和数据复盘。',background:'院校通常不是唯一门槛，真实作品、账号数据和活动结果更容易证明能力。',caution:'不仅靠灵感，需要持续生产、接受数据反馈并不断修改。',reasons:['与你选择的写作表达或创造活动相关','可以快速形成作品','能够从校园场景低成本实践'],case:'学校要举办一场“第一次找实习”分享会。过去推文标题是《就业指导中心举办实习经验分享会》，阅读量只有平均水平的一半。目标用户是从未投过简历、担心自己没有经历的大二学生。',questions:['指出原题目为什么可能无法吸引目标学生','写出三个角度不同的新标题','选择一个标题，写出80字开头并说明想触发什么行动'],focus:'根据具体人群调整选题与表达，而不是只追求文采。',next:'找三位目标同学做标题选择测试',purpose:'用真实选择验证内容是否打中了目标人群，而不是让你凭个人喜好判断好坏。'},
operations:{name:'项目运营',type:'能力迁移',desc:'把目标拆成任务，协调时间、人员和资源，让项目按计划发生。',work:'制定计划、分配任务、跟踪进度、处理风险并复盘结果。',skills:'目标拆解、时间管理、沟通协调、风险预判和复盘。',background:'入门岗位通常重视真实活动与项目经历；学校背景有影响，但可用执行成果和复盘证明能力。',caution:'需要同时处理多个细节和临时变化，成果往往来自团队而非个人。',reasons:['与你选择的组织或推进活动相关','校园经历能够迁移','短案例可观察规划和风险意识'],case:'你要在14天后组织一场50人的校园职业分享会。场地尚未确认，嘉宾只能提前3天确定最终时间，宣传至少需要7天，团队共有4人。',questions:['列出最关键的五项任务和截止时间','指出任务之间的依赖关系','识别两个最大风险，并分别给出备用方案'],focus:'在约束条件下安排优先级、依赖关系和风险。',next:'把方案做成一页执行看板',purpose:'验证你是否享受把复杂事情变成清晰计划，并留下可复用的项目成果。'},
hr:{name:'人力资源',type:'兴趣迁移',desc:'通过结构化判断帮助团队找到、发展并留住合适的人。',work:'分析岗位需求、筛选候选人、组织面试、支持培训与员工发展。',skills:'沟通、信息判断、结构化面试、规则意识和组织理解。',background:'多数入门岗位重视实习和沟通实践；部分大企业会筛选院校背景。',caution:'并非只是与人聊天，还涉及大量流程、数据、规则和困难沟通。',reasons:['与你选择的沟通或帮助他人相关','可以从招新场景体验','能力可跨专业迁移'],case:'学生会要招募活动负责人。候选人甲组织过三次活动但表达紧张；候选人乙表达流畅但没有项目经历。岗位最重要的是按期推进多人协作，并在突发情况中解决问题。',questions:['列出这个岗位最重要的三项能力','分别为两位候选人设计两个追问','制定一条统一评分标准，避免只凭“聊得投机”做决定'],focus:'从岗位需要出发收集证据，而不是凭第一印象评价人。',next:'用评分表复盘一次真实招新',purpose:'验证你是否愿意在“理解人”的同时保持结构化和公平判断。'}};
const assessments={
finance:{choices:[{q:'本月利润是多少？',options:['1万元','2万元','3万元'],correct:1},{q:'最值得优先关注的变化是？',options:['房租没有变化','收入下降且人工上升','原料成本下降'],correct:1}],keywords:['利润','收入','人工','客流','订单','单价','同比'],reference:'本月利润为2万元，上月利润为4万元。虽然仍盈利，但利润下降50%。最值得追问的是收入减少2万元、人工增加0.2万元。还需查看客流/订单量、客单价、促销、营业天数等，才能判断经营原因。'},
data:{choices:[{q:'周四最明显的异常是？',options:['新增用户和留存同时提高','新增用户大增但留存显著下降','所有指标都没有变化'],correct:1},{q:'仅凭现有数据能否判断广告有效？',options:['可以，新增用户最多','不可以，还缺少来源和后续质量数据','可以，因为周四投了广告'],correct:1}],keywords:['渠道','来源','成本','转化','留存','活跃','对照'],reference:'周四新增用户从约120—150跃升到400，但次日留存从约40%降到18%。不能仅凭新增量判断广告有效。至少还需要广告来源用户占比、获客成本、后续7日留存/活跃、付费或关键行为转化，并与未投放日期或人群比较。'},
product:{choices:[{q:'案例中更核心的问题是？',options:['页面颜色不好看','关键信息出现太晚，用户付出多步操作后才知道无座','用户不应该高峰期预约'],correct:1},{q:'更小且直接的改进是？',options:['重做整个校园App','在选择日期后直接显示各楼栋余位并支持筛选','增加更多宣传海报'],correct:1}],keywords:['用户','场景','高峰','余位','步骤','信息','筛选'],reference:'目标用户是高峰期需要快速找到座位的学生。核心问题不是单纯步骤多，而是“余位信息出现太晚”，导致用户完成多步操作后才发现无座。最小方案是在选择日期/时段后聚合展示楼栋与房间余位，并允许按有座筛选。'},
content:{choices:[{q:'旧标题最主要的问题是？',options:['字数太少','只描述主办方动作，没有回应学生焦虑和收益','没有使用感叹号'],correct:1},{q:'更贴近目标学生的角度是？',options:['中心工作总结','零经历学生如何迈出第一步','会议举办地点介绍'],correct:1}],keywords:['目标','焦虑','零经历','收益','行动','实习','简历'],reference:'旧标题从主办方视角描述事件，没有回应“没有经历、不敢投”的学生焦虑。可改为《没有实习经历，大二现在开始还来得及吗？》。开头应承认焦虑、说明能获得的具体方法，并引导报名。'},
operations:{choices:[{q:'哪项工作应最先推进？',options:['活动结束后的复盘','同时锁定场地备选和嘉宾可用时段','制作现场感谢信'],correct:1},{q:'最大的依赖冲突是什么？',options:['宣传需要7天，但嘉宾最终时间仅提前3天确定','团队只有4人','活动有50人参加'],correct:0}],keywords:['场地','嘉宾','宣传','截止','依赖','风险','备选'],reference:'应立即并行确认场地备选与嘉宾可用时间范围。关键冲突是宣传至少需7天，而最终时间提前3天才确定。可先锁定时间窗口并制作可快速更新的宣传模板，同时准备场地和线上直播两个备选。'},
hr:{choices:[{q:'本岗位最该优先验证的是？',options:['表达是否流畅','是否有按期推进协作和处理突发情况的证据','是否与面试官兴趣相同'],correct:1},{q:'更公平的做法是？',options:['凭第一印象决定','对两位候选人使用相同问题和评分标准','只看过去头衔'],correct:1}],keywords:['证据','推进','协作','突发','标准','追问','评分'],reference:'岗位核心能力是推进协作、风险处理和责任意识。应让两位候选人回答相同的行为问题，如“讲一次进度落后时你如何处理”，并按情境、行动、结果和复盘统一评分，不能把表达流畅等同于胜任。'}};
const roleLibrary=[['核算会计','专业直接相关','专业对口'],['财务分析','专业直接相关','专业对口'],['审计','专业直接相关','专业对口'],['税务','专业直接相关','专业对口'],['资金管理','专业直接相关','专业对口'],['内控与风险','财会延伸','专业延伸'],['财务BP','财会延伸','专业延伸'],['ERP实施顾问','财会延伸','专业可迁移'],['商业分析','能力迁移','跨专业可探索'],['数据分析','能力迁移','跨专业可探索'],['解决方案顾问','能力迁移','跨专业可探索'],['企业运营','能力迁移','跨专业可探索']];
const roleDetails={
'核算会计':{summary:'记录和核对企业经济业务，确保账务与报表准确。',daily:'审核单据、制作凭证、月末结账、往来核对并协助出具财务报表。新人通常从费用、应收应付或固定资产模块开始。',hard:['会计准则与三张财务报表','Excel与财务软件','凭证、结账和往来核对','税务申报基础'],soft:['细节与责任意识','按截止日期完成工作的稳定性','发现异常后主动追问','与业务解释单据规范'],cert:'初级会计职称有一定帮助，但不能替代实操。CPA不是入门必需；应根据长期方向决定，不建议大一盲目备考。',education:'多数基础岗位院校依赖中低；大型集团、事务所和管培项目可能提高学历与院校要求。',path:['大一：学好会计基础和Excel','大二：完成账务模拟项目，可选择初级会计','大三：寻找企业财务或事务所实习','大四：准备校招并补齐报表与税务实操'],related:['审计','税务','财务分析']},
'财务分析':{summary:'从财务和经营数据解释企业表现，为预算和决策提供依据。',daily:'比较预算与实际、分析收入成本变化、制作经营报告，并向业务部门解释异常。',hard:['财务报表与管理会计','Excel建模和数据透视','预算与差异分析','SQL或可视化属于加分项'],soft:['业务理解与追问能力','把数字翻译成经营语言','结论表达','跨部门沟通'],cert:'没有统一必备证书。初级会计或CPA科目可证明基础，但项目、实习和分析作品通常更直接。',education:'大型企业和高薪管培岗位较看重学历与院校；普通院校可通过实习、作品、工具和行业理解弥补。',path:['大一：财务报表与Excel','大二：完成经营分析案例，学习基础SQL','大三：争取FP&A、经营分析或财务实习','大四：准备案例面试和分析作品'],related:['财务BP','商业分析','管理会计']},
'审计':{summary:'检查财务信息和业务流程是否真实、合规并有效控制风险。',daily:'抽查凭证、执行盘点、核对数据、访谈业务人员、记录审计证据并形成底稿。',hard:['审计程序与会计准则','Excel和抽样检查','审计底稿','风险与内控基础'],soft:['职业怀疑与证据意识','耐心和细节','沟通追问','高峰期时间管理'],cert:'CPA对长期发展价值较高，但并非实习前提。初期先理解审计工作和取得实习，再决定长期投入。',education:'头部会计师事务所和优质项目会筛选院校、学历、英语与实习；中小所更重视基础和稳定性。',path:['大一：会计基础与英语','大二：审计基础、Excel和案例','大三：事务所实习并判断是否接受工作节奏','大四：校招，按目标决定CPA规划'],related:['内控与风险','核算会计','税务']},
'税务':{summary:'处理企业纳税申报、税务合规和业务中的税务影响。',daily:'整理涉税数据、完成申报、跟踪政策、处理发票和协助税务咨询。',hard:['税法与主要税种','申报流程和发票管理','Excel与数据核对','政策检索'],soft:['合规意识','持续学习政策','严谨表达','与业务解释税务影响'],cert:'税务师和CPA税法有帮助，但不是所有入门岗位必需。应先确认自己是否愿意长期跟踪政策。',education:'一般岗位院校影响中等；大型咨询机构和复杂税务项目更看重学历、院校和专业能力。',path:['大一：会计与经济法基础','大二：税法案例和申报模拟','大三：税务、财务或事务所实习','大四：根据目标选择税务师或CPA'],related:['核算会计','审计','内控与风险']},
'资金管理':{summary:'管理企业现金、收付款、融资与资金安全。',daily:'监控账户余额、安排收付款、制作资金计划、对接银行并管理融资资料。',hard:['现金流与资金计划','银行结算和票据','Excel资金预测','融资基础'],soft:['风险意识','准确与及时','跨部门协调','面对资金压力时保持判断'],cert:'通常没有统一必备证书。银行、财务实习和现金流分析经历比泛化证书更重要。',education:'大型集团资金部或金融机构合作岗位可能更看重学历；一般企业更看重经验和可靠性。',path:['大一：理解现金流量表','大二：完成资金计划案例','大三：财务共享、银行或资金岗实习','大四：准备资金预测与融资基础面试'],related:['财务分析','核算会计','财务BP']},
'内控与风险':{summary:'识别业务流程中的错误、舞弊与合规风险，并设计控制措施。',daily:'梳理流程、访谈岗位、检查控制执行、记录缺陷并推动整改。',hard:['内部控制框架','流程图与风险矩阵','审计与合规基础','数据检查'],soft:['系统思考','独立判断','敏感但有分寸的沟通','推动整改'],cert:'CIA等证书对长期内审发展有帮助，但不是本科入门必需。初期更应积累流程和审计案例。',education:'大型企业和咨询机构会关注学历与项目经验；普通院校可通过内审实习和流程作品弥补。',path:['大一：会计和管理基础','大二：学习流程图、风险矩阵','大三：内审、审计或合规实习','大四：准备流程案例与风险判断'],related:['审计','税务','ERP实施顾问']},
'财务BP':{summary:'连接财务与业务团队，用数据支持经营目标和资源配置。',daily:'参与业务会议、分析经营指标、做预算预测，并推动业务部门采取行动。',hard:['财务分析与预算','业务指标体系','Excel/SQL','行业经营逻辑'],soft:['影响力与沟通','商业敏感度','冲突处理','推动决策'],cert:'没有必备证书。CPA或管理会计知识可加分，但业务理解、沟通和经营分析经历更关键。',education:'优质财务BP岗位较看重学历、平台和经验，通常不是真正零经验岗位，可先从财务分析进入。',path:['大一：财务报表与表达','大二：经营分析项目和SQL基础','大三：财务分析或业务运营实习','大四：以分析岗为入口，逐步向BP发展'],related:['财务分析','商业分析','企业运营']},
'ERP实施顾问':{summary:'帮助企业把财务和业务流程配置进ERP系统并完成落地。',daily:'调研流程、配置系统、整理数据、测试功能、培训用户和解决上线问题。',hard:['财务业务流程','ERP基本模块','需求文档与测试','数据整理'],soft:['客户沟通','问题定位','项目推进','学习复杂系统'],cert:'厂商认证可能对特定生态有帮助，但不是通用必需。应先确认目标系统和企业，再决定是否考证。',education:'院校影响通常中等，企业更看重财务流程理解、系统学习能力和项目经验。',path:['大一：会计流程与Excel','大二：体验ERP沙盘或系统课程','大三：实施、信息化或财务数字化实习','大四：准备流程分析和客户沟通案例'],related:['解决方案顾问','内控与风险','财务分析']},
'商业分析':{summary:'结合数据和业务问题，为产品、市场或经营决策提供分析。',daily:'定义指标、分析数据、研究业务原因、制作报告并提出行动建议。',hard:['Excel/SQL','统计与指标设计','数据可视化','商业问题拆解'],soft:['结构化思考','沟通表达','好奇与追问','避免草率归因'],cert:'通常没有必备证书。证书价值低于完整分析项目、SQL能力和实习成果。',education:'头部互联网和咨询岗位可能看重院校；可通过高质量项目、比赛和行业分析作品弥补。',path:['大一：Excel和商业基础','大二：SQL与两个完整分析项目','大三：数据、经营或策略实习','大四：准备案例题和作品集'],related:['数据分析','财务分析','财务BP']},
'数据分析':{summary:'清洗、计算并解释数据，帮助团队发现问题和验证决策。',daily:'提取数据、检查质量、计算指标、制作图表并解释变化。',hard:['Excel、SQL','基础统计','数据可视化','数据清洗'],soft:['逻辑与严谨','业务理解','解释不确定性','需求沟通'],cert:'没有统一必备证书。工具证书通常不如真实项目有效，不建议只靠考证证明能力。',education:'院校影响因企业而异；作品、实习、SQL测试和业务分析能力常被直接考察。',path:['大一：Excel和统计基础','大二：SQL、可视化和公开数据项目','大三：数据相关实习','大四：作品集与SQL案例面试'],related:['商业分析','财务分析','企业运营']},
'解决方案顾问':{summary:'理解客户业务问题，组合产品与服务形成可落地方案。',daily:'访谈客户、梳理需求、演示产品、制作方案并协调技术和销售。',hard:['行业与产品知识','需求分析','方案文档与演示','基础项目管理'],soft:['倾听和提问','表达说服','关系协调','快速学习'],cert:'通常无通用必备证书。若聚焦云、ERP或特定软件，相关厂商认证才可能有价值。',education:'院校影响中等，客户沟通、行业理解、演示能力和实习经历更关键。',path:['大一：表达、财会流程和演示','大二：做一份企业问题解决方案','大三：咨询、售前或实施实习','大四：准备方案演示与客户案例'],related:['ERP实施顾问','财务BP','企业运营']},
'企业运营':{summary:'围绕业务目标协调资源、流程和团队，推动项目持续运行。',daily:'跟踪指标、处理流程问题、协调部门、推进项目并复盘结果。',hard:['Excel与基础分析','流程与项目管理','运营指标','文档和看板'],soft:['执行与协调','优先级判断','应变能力','复盘意识'],cert:'通常不需要职业证书。项目成果、活动数据和实习经历更能证明能力。',education:'多数岗位院校影响中等；行业头部项目会提高筛选标准。',path:['大一：参与校园项目并记录成果','大二：学习数据和项目管理','大三：运营或项目实习','大四：用量化项目经历准备校招'],related:['财务BP','商业分析','解决方案顾问']}};
const openCases={
finance:{case:'你在一家电商公司协助做月度经营分析。服装品类销售额增长25%，退货率却从18%升至34%，同期平台广告费增长40%。负责人认为“销售增长说明本月表现优秀”。',questions:['你是否同意负责人判断，为什么','退货率和广告费变化可能怎样影响真实利润','为了形成结论，你还需要查看哪些经营数据'],keywords:['退货','利润','广告','毛利','成本','客单价','转化'],reference:'销售额增长不能直接代表经营改善。高退货会冲减收入并增加物流处理成本，广告费增长也可能降低利润。应补充净销售额、毛利率、广告投入产出、退货原因、获客成本和复购数据。'},
data:{case:'校园食堂推出夜宵窗口后，晚上营业额增加60%，但投诉数量从每周5起增加到22起。校方询问是否应该扩大夜宵窗口。你只拿到营业额、投诉数和营业时间三项数据。',questions:['现有数据支持扩大窗口吗','投诉增加可能有哪些不同解释','设计一个最小分析方案，说明需要补充的数据和比较方式'],keywords:['客流','订单','投诉率','品类','时段','对照','成本'],reference:'不能仅比较营业额和投诉绝对数。需要计算每千单投诉率，补充客流、订单量、品类、等待时间、成本和满意度，并与未开放窗口或开放前相同日期进行对照。'},
product:{case:'学校电子门禁App更新后，学生反馈“扫码太慢”。研发认为只要提升二维码加载速度即可，但运营发现很多投诉发生在手机无网络时。',questions:['重新定义这个问题，不要只复述“扫码太慢”','研发方案可能漏掉了什么场景','提出一个最小验证方法和一个备选方案'],keywords:['用户','场景','网络','加载','离线','验证','门禁'],reference:'问题应定义为学生在弱网或无网进入校园时无法及时展示通行凭证。仅优化在线加载可能无效。可统计投诉网络环境并做弱网测试，方案可包括离线缓存限时二维码或本地凭证。'},
content:{case:'校园心理活动推文《拥抱情绪，向阳而生》阅读量很高，但实际报名人数很少。评论区有人问“活动到底做什么”“会不会公开个人信息”。',questions:['为什么高阅读量没有转化为报名','重新设计内容结构和核心信息顺序','提出两个可以验证改版是否有效的指标'],keywords:['目标','隐私','内容','报名','转化','流程','信任'],reference:'标题可能吸引点击，但正文没有及时解释活动内容、参与方式和隐私保护，导致信任与行动成本过高。应优先说明适合谁、做什么、隐私规则和报名流程，并观察报名转化率与页面退出位置。'},
operations:{case:'社团计划在两周内完成一次跨校比赛。已有80人报名，但场地只能容纳50人；赞助商要求现场展示，裁判只有周六有空，而场地方只确认了周日。',questions:['列出当前最关键的三个冲突','给出决策顺序和需要立刻确认的人','设计主方案和一个可执行的备用方案'],keywords:['场地','裁判','报名','赞助','优先级','备选','沟通'],reference:'应先处理决定活动能否成立的时间冲突，再处理容量和赞助展示。需立即与裁判、场地方和赞助商确认底线；备选可包括更换场地、分场次或部分环节线上化。'},
hr:{case:'一家创业团队招聘运营实习生。岗位需要独立写内容、每周分析数据并与销售协作。候选人甲有公众号作品但没有数据经验；候选人乙学过数据分析但没有公开作品。',questions:['把岗位要求拆成可观察的评价维度','分别设计一项任务验证两位候选人的短板','如何综合评分并避免偏爱与自己相似的人'],keywords:['作品','数据','协作','任务','标准','权重','证据'],reference:'可按内容质量、数据意识、协作沟通和学习能力设置统一维度与权重。给甲数据复盘任务，给乙内容样稿任务；使用同一评分表和行为证据，避免凭个人好感判断。'}};
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo({top:0,behavior:'smooth'})}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._);t._=setTimeout(()=>t.classList.remove('show'),2300)}
function bindChoices(id,key){$('#'+id).onclick=e=>{if(e.target.tagName!=='BUTTON')return;const v=e.target.dataset.value,a=state[key];if(a.includes(v)){state[key]=a.filter(x=>x!==v);e.target.classList.remove('selected')}else if(a.length<5){a.push(v);e.target.classList.add('selected')}else toast('最多选择 5 项')}}
bindChoices('interestChoices','interests');bindChoices('valueChoices','values');
const preferenceItems=[
['课程项目要求很模糊，你通常先做什么？','先做一个最小版本，再根据反馈调整','先搜集案例，把要求研究清楚','行动验证','研究理解'],
['接触一个陌生软件时，你更可能：','直接点开功能边用边学','先看教程了解整体结构','行动验证','研究理解'],
['有一个新想法时，你倾向：','尽快找人试一试','先独立推演可能的问题','行动验证','研究理解'],
['团队进度落后时，你更自然地：','召集大家沟通并重新分工','先独立梳理原因和方案','沟通推动','独立深思'],
['讨论中出现分歧时，你通常：','通过交流促成一个可执行决定','先沉默思考，再给出完整观点','沟通推动','独立深思'],
['完成重要任务后，你更愿意：','向他人展示并收集反馈','自己复盘并继续打磨','沟通推动','独立深思'],
['两个方案各有优缺点时，你更看重：','数据、规则和可验证结果','使用者的感受与关系影响','逻辑证据','体验关怀'],
['同学没有完成分工时，你首先关注：','任务标准和实际影响','对方遇到了什么困难','逻辑证据','体验关怀'],
['评价一项活动是否成功，你更依赖：','目标完成率和结果数据','参与者的真实体验','逻辑证据','体验关怀'],
['距离截止还有两周，你通常：','提前拆解节点并逐项完成','保留空间，根据变化调整','结构计划','灵活探索'],
['旅行或活动开始前，你更喜欢：','确定主要安排和备选方案','到现场根据兴趣决定','结构计划','灵活探索'],
['遇到计划外机会时，你更可能：','先检查是否影响原目标','先尝试，再决定是否调整计划','结构计划','灵活探索']];
$('#preferenceQuestions').innerHTML=preferenceItems.map((x,i)=>`<fieldset class="scenario-question"><legend>${i+1}. ${x[0]}</legend><label><input type="radio" name="pref${i+1}" value="${x[3]}"><span>${x[1]}</span></label><label><input type="radio" name="pref${i+1}" value="${x[4]}"><span>${x[2]}</span></label></fieldset>`).join('')+`<button class="primary-btn wizard-next" id="buildPortrait">生成我的基础画像 →</button><p class="privacy">结果仅描述当前倾向，不判断能力高低，也不构成正式心理测评。</p>`;
function choose(major,i){let a=[];if(/会计|财务|金融|经济/.test(major))a.push('finance');else if(/计算|数学|统计|工程/.test(major))a.push('data');else if(/中文|新闻|传播|广告/.test(major))a.push('content');else a.push('operations');if(i.some(x=>/分析|工具|研究/.test(x)))a.push('data');if(i.some(x=>/写作|视觉/.test(x)))a.push('content');if(i.some(x=>/组织|协调/.test(x)))a.push('operations');if(i.some(x=>/沟通|帮助|说服/.test(x)))a.push('hr');a.push('product','data','operations','content','hr');return [...new Set(a)].slice(0,3)}
$('#toInterests').onclick=()=>{const major=$('#major').value.trim();if(!$('#grade').value||!major)return toast('请先填写年级和专业');if(!/会计|财务|审计|金融|经济|税务/.test(major))return toast('当前MVP仅支持财会、金融和经济相关专业');show('interestsScreen')};
$('#backToProfile').onclick=()=>show('profileScreen');
$('#toPreferences').onclick=()=>{if(!state.interests.length||!state.values.length)return toast('请至少选择一项活动和一项工作偏好');if(!$('input[name=clarity]:checked'))return toast('请选择当前方向状态');show('preferenceScreen')};
$('#backToInterests').onclick=()=>show('interestsScreen');
function buildPortrait(){const answers=preferenceItems.map((_,i)=>$(`input[name=pref${i+1}]:checked`)?.value);if(answers.some(x=>!x))return toast('请完成全部12道情境题');const counts={};answers.forEach(x=>counts[x]=(counts[x]||0)+1);const dimensions=[['行动验证','研究理解'],['沟通推动','独立深思'],['逻辑证据','体验关怀'],['结构计划','灵活探索']];const preferences=dimensions.map(d=>(counts[d[0]]||0)>=(counts[d[1]]||0)?d[0]:d[1]);state.profile={grade:$('#grade').value,major:$('#major').value.trim(),interests:[...state.interests],values:[...state.values],clarity:$('input[name=clarity]:checked').value,preferences,startedAt:new Date().toISOString()};state.careers=choose(state.profile.major,state.interests);state.index=0;state.results=[];$('#portraitTitle').textContent=`${state.profile.major} · ${preferences.slice(0,2).join(' × ')}`;$('#portraitIntro').textContent=`你目前更偏向${preferences.join('、')}。这是一份用于职业探索的初步画像，需要在真实任务中继续验证。`;$('#portraitTags').innerHTML=preferences.map(x=>`<span>${x}</span>`).join('');$('#portraitStrengths').textContent=preferences.includes('逻辑证据')?'分析信息、依据证据判断，并保持标准一致。':'理解他人体验、识别关系影响，并从人的需要出发。';$('#portraitEnergy').textContent=preferences.includes('沟通推动')?'需要协作、表达和推动结果的任务。':'允许独立思考、深入研究并形成完整观点的任务。';$('#portraitCaution').textContent=preferences.includes('结构计划')?'面对快速变化时的调整能力，以及是否会因追求计划而降低探索意愿。':'长期任务中的节奏管理，以及是否会因保留弹性而推迟关键行动。';$('#portraitValues').textContent=state.values.join('、');show('portraitScreen')}
$('#buildPortrait').onclick=buildPortrait;$('#backToPreferences').onclick=()=>show('preferenceScreen');$('#portraitPartial').onclick=()=>show('clarifyScreen');$('#backToPortrait').onclick=()=>show('portraitScreen');$('#rebuildPortrait').onclick=()=>{const extra=[1,2,3,4].map(i=>$(`input[name=clarify${i}]:checked`)?.value);if(extra.some(x=>!x))return toast('请完成四道补充问题');state.profile.clarifications=extra;$('#portraitIntro').textContent=`结合补充回答，你目前更偏向${state.profile.preferences.join('、')}，同时表现出${extra.slice(0,2).join('、')}的特点。画像用于提出更合适的探索方向，而不是给你贴标签。`;$('#portraitStrengths').textContent+=` 补充证据显示，你在“${extra[0]}”和“${extra[1]}”类任务中更容易获得他人认可。`;$('#portraitCaution').textContent=`你明确${extra[2]}。后续岗位案例会重点验证“${extra[3]}”是否能持续给你成就感。`;$('#portraitTags').innerHTML=[...state.profile.preferences,...extra.slice(0,2)].map(x=>`<span>${x}</span>`).join('');show('portraitScreen')};$('#portraitConfirm').onclick=()=>{renderCareer();show('careerScreen')};
function current(){return careers[state.careers[state.index]]}
function setResult(result){const i=state.results.findIndex(x=>x.key===result.key);if(i>=0)state.results[i]=result;else state.results.push(result)}
function renderCareer(){const c=current();$('#directionCount').textContent=`候选方向 ${state.index+1} / ${state.careers.length} · ${c.type}`;$('#careerTitle').textContent=c.name;$('#careerDesc').textContent=c.desc;$('#careerReasons').innerHTML=c.reasons.map(x=>`<li>${x}</li>`).join('');$('#careerWork').textContent=c.work;$('#careerSkills').textContent=c.skills;$('#careerBackground').textContent=c.background;$('#careerCaution').textContent=c.caution;$('#profileTags').innerHTML=(state.profile.preferences||[]).map(x=>`<span>${x}</span>`).join('');$('#sequenceDots').innerHTML=state.careers.map((_,i)=>`<span class="${i<state.index?'done':i===state.index?'current':''}">${i+1}</span>`).join('');$('#previousDirectionBtn').textContent=state.index?'← 查看上一个候选方向':'← 返回个人画像'}
$('#notInterestedBtn').onclick=()=>{setResult({key:state.careers[state.index],name:current().name,decision:'暂时不感兴趣',answer:'',feeling:'未体验',verdict:'暂不继续'});advance()};
$('#previousDirectionBtn').onclick=()=>{if(state.index>0){state.index--;renderCareer();show('careerScreen')}else show('portraitScreen')};
$('#interestedBtn').onclick=()=>{state.mode='guided';prepareTask();show('taskScreen')};
function prepareTask(){
  const key=state.careers[state.index],c=current(),a=assessments[key],open=openCases[key];
  const v=state.mode==='guided'?{case:c.case,questions:c.questions}:open;
  state.activeAssessment=state.mode==='guided'?a:{...open,choices:[]};
  $('#taskModeLabel').textContent=state.mode==='guided'?'案例A · 引导分析题':'案例B · 迁移挑战题';
  $('#backToCareer').textContent=state.mode==='guided'?'← 返回方向介绍':'← 返回基础案例反馈';
  $('#answerHint').textContent=state.mode==='guided'?'选择题提供脚手架，文字理由仍由你独立完成':'尝试沿用基础案例的“发现变化—解释影响—补充证据”方法';
  $('#taskTitle').textContent=`案例：${c.name}`;$('#taskCareer').textContent=c.name;$('#caseBackground').textContent=v.case;
  $('#taskBrief').innerHTML=`<h3>${state.mode==='guided'?'最后请说明你的理由':'请完成以下判断'}</h3><ol>${v.questions.map(x=>`<li>${x}</li>`).join('')}</ol>`;
  $('#guidedQuestions').innerHTML=state.mode==='guided'?a.choices.map((q,i)=>`<fieldset class="choice-question"><legend>${i+1}. ${q.q}</legend>${q.options.map((o,j)=>`<label><input type="radio" name="caseChoice${i}" value="${j}"> ${o}</label>`).join('')}</fieldset>`).join(''):'';
  $('#abilityFocus').textContent=c.focus;$('#taskAnswer').value='';$('#taskFeeling').value='';
  const supported=!!(window.SpeechRecognition||window.webkitSpeechRecognition);$('#voiceBtn').disabled=!supported;$('#voiceNote').textContent=supported?'语音识别可用。首次使用时浏览器会请求麦克风权限。':'当前浏览器不提供网页语音识别能力，请使用系统听写或键盘输入。';
}
$('#backToCareer').onclick=()=>show('careerScreen');
let recognition=null;$('#voiceBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('该浏览器未提供语音识别接口，可使用系统听写');if(recognition){recognition.stop();return}recognition=new SR();recognition.lang='zh-CN';recognition.continuous=true;recognition.interimResults=true;let base=$('#taskAnswer').value;recognition.onstart=()=>{$('#voiceBtn').textContent='■ 停止语音';$('#voiceNote').textContent='正在听写。请靠近麦克风，并保持网络连接。'};recognition.onresult=e=>{let final='',temp='';for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0].transcript;e.results[i].isFinal?final+=s:temp+=s}if(final){base+=(base?'\n':'')+final;$('#taskAnswer').value=base}$('#taskAnswer').placeholder=temp||'正在听写……'};recognition.onerror=e=>{const reasons={not_allowed:'未获得麦克风权限，请在浏览器设置中允许访问。','audio-capture':'没有检测到可用麦克风。',network:'语音识别服务需要网络连接，但当前连接失败。','no-speech':'没有检测到清晰语音，请靠近麦克风后重试。'};$('#voiceNote').textContent=reasons[e.error]||`语音识别失败（${e.error}），请改用键盘或系统听写。`;toast($('#voiceNote').textContent)};recognition.onend=()=>{recognition=null;$('#voiceBtn').textContent='🎙 语音输入'};recognition.start()};
function evaluateAnswer(answer,a){let keywordHits=a.keywords.filter(k=>answer.includes(k));let choiceCorrect=0,choiceTotal=state.mode==='guided'?a.choices.length:0;if(state.mode==='guided'){for(let i=0;i<a.choices.length;i++){const v=$(`input[name=caseChoice${i}]:checked`);if(!v)return{error:'请完成全部选择题'};if(Number(v.value)===a.choices[i].correct)choiceCorrect++}}const choiceScore=choiceTotal?Math.round(choiceCorrect/choiceTotal*40):30;const depth=Math.min(30,Math.round(answer.length/4));const keywordScore=Math.min(30,keywordHits.length*6);return{score:Math.min(100,choiceScore+depth+keywordScore),choiceCorrect,choiceTotal,keywordHits}}
$('#submitTask').onclick=()=>{const answer=$('#taskAnswer').value.trim(),feeling=$('#taskFeeling').value,c=current(),a=state.activeAssessment;if(answer.length<40)return toast('请回答案例问题并说明理由，至少写下40个字');if(!feeling)return toast('请选择完成任务时的真实感受');const ev=evaluateAnswer(answer,a);if(ev.error)return toast(ev.error);const positive=/很投入|有一点兴趣/.test(feeling);state.results.push({key:state.careers[state.index],name:c.name,decision:'感兴趣并体验',answer,feeling,score:ev.score,verdict:positive?'值得继续探索':'暂不优先'});$('#scoreValue').textContent=ev.score;$('#feedbackTitle').textContent=`「${c.name}」案例反馈`;$('#feedbackSummary').textContent='这个分数代表本次案例回答的完整程度，不是职业能力认证。开放案例可能存在多种合理答案。';$('#choiceResult').textContent=ev.choiceTotal?`${ev.choiceCorrect} / ${ev.choiceTotal} 题正确`:'按分析框架评估';$('#answerResult').textContent=`命中 ${ev.keywordHits.length} 个关键视角`;$('#directionVerdict').textContent=positive?'值得继续探索':'暂不优先';$('#rubricFeedback').innerHTML=`<h3>你的回答反馈</h3><ul><li>${answer.length>=100?'表达较完整，包含了足够的判断过程。':'已形成基本判断，可进一步补充原因和数据需求。'}</li><li>${ev.keywordHits.length>=3?'覆盖了多个岗位关键视角：'+ev.keywordHits.join('、'):'建议补充岗位常用视角，例如：'+a.keywords.slice(0,4).join('、')+'。'}</li><li>${ev.choiceTotal&&ev.choiceCorrect<ev.choiceTotal?'选择题存在偏差，请结合参考答案理解判断逻辑。':'基础判断方向合理，下一步重点是让依据更具体。'}</li></ul>`;$('#referenceAnswer').innerHTML=`<p>${a.reference}</p><p><b>评分说明：</b>基础判断40分、回答完整度30分、关键分析视角30分。文字关键词只用于演示版初步反馈，正式产品需由评分规则或AI结合人工复核。</p>`;$('#nextAction').textContent=c.next;$('#actionPurpose').textContent=c.purpose+' 完成这一步后，你应留下一个可比较、可复盘的成果；如果你仍不愿继续，便可以有依据地降低该方向优先级。';$('#continueBtn').textContent=state.index<state.careers.length-1?'查看下一个候选方向 →':'生成本次探索结论 →';show('feedbackScreen')};
$('#continueBtn').onclick=()=>advance();
$('#backToTask').onclick=()=>show('taskScreen');
function advance(){state.index++;if(state.index<state.careers.length){renderCareer();show('careerScreen')}else renderFinal()}
function renderFinal(){$('#summaryGrid').innerHTML=state.results.map((r,i)=>`<article class="summary-card"><span>方向 0${i+1}</span><h3>${r.name}</h3><b class="verdict">${r.verdict}</b><p>${r.decision==='暂时不感兴趣'?'了解工作内容后选择不继续，已形成一条排除证据。':`案例完成度：${r.score||'—'} 分｜感受：${r.feeling}`}</p></article>`).join('');const pos=state.results.filter(r=>r.verdict==='值得继续探索');if(pos.length){$('#finalAdvice').textContent=`优先继续了解：${pos.map(x=>x.name).join('、')}`;$('#finalWhy').textContent='这三个方向只是根据当前信息选出的第一轮样本。建议优先深化有兴趣且案例完成度较高的方向，同时到职业方向库查看相邻岗位与跨专业岗位。'}else{$('#finalAdvice').textContent='暂不锁定职业，继续扩大探索样本';$('#finalWhy').textContent='三个方向都没有形成强兴趣，不代表你没有适合的工作。请到职业方向库换一个工作类型继续体验。'}show('finalScreen')}
function saveRecord(){const records=JSON.parse(localStorage.getItem('career_mvp_records')||'[]');records.unshift({id:Date.now(),profile:state.profile,results:state.results,completedAt:new Date().toISOString()});localStorage.setItem('career_mvp_records',JSON.stringify(records.slice(0,50)));toast('结果已保存到本机测试记录')}
$('#saveFinishBtn').onclick=()=>{saveRecord();$('#saveFinishBtn').textContent='已保存';$('#saveFinishBtn').disabled=true};
function reset(){state.interests=[];state.values=[];state.careers=[];state.results=[];state.index=0;$$('.choice-grid button').forEach(x=>x.classList.remove('selected'));$$('input[type=radio]').forEach(x=>x.checked=false);$('#grade').value='';$('#major').value='';$('#saveFinishBtn').disabled=false;$('#saveFinishBtn').textContent='保存结果';show('profileScreen')}
$('#restartBtn').onclick=reset;$('#resetBtn').onclick=reset;
$('#backFromFinal').onclick=()=>{state.index=Math.max(0,state.careers.length-1);renderCareer();show('careerScreen')};
$('#recordsBtn').onclick=()=>{state.returnScreen=$$('.screen.active')[0]?.id||'profileScreen';renderRecords();show('recordsScreen')};$('#backFromRecords').onclick=()=>show(state.returnScreen==='recordsScreen'?'profileScreen':state.returnScreen);
function renderRecords(){const rs=JSON.parse(localStorage.getItem('career_mvp_records')||'[]');$('#recordsList').innerHTML=rs.length?rs.map(r=>`<article class="record-card"><div><small>${new Date(r.completedAt).toLocaleString('zh-CN')}</small><h3>${r.profile.grade} · ${r.profile.major}</h3><p>${r.profile.clarity}｜兴趣：${r.profile.interests.join('、')}</p></div><div>${r.results.map(x=>`<span><b>${x.name}</b> ${x.verdict}</span>`).join('')}</div></article>`).join(''):'<div class="empty-records">还没有保存的测试记录。完成一次完整测试后，结果会出现在这里。</div>'}
$('#exportBtn').onclick=()=>{const data=localStorage.getItem('career_mvp_records')||'[]',blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='职业探索测试记录.json';a.click();URL.revokeObjectURL(a.href)};
function renderExplorer(filter='全部'){$('#explorerGrid').innerHTML=roleLibrary.filter(x=>filter==='全部'||x[1]===filter).map(x=>`<button class="role-card" data-role="${x[0]}"><span>${x[1]}</span><h3>${x[0]}</h3><b>${x[2]}</b><p>查看工作内容、能力、证书和准备路径 →</p></button>`).join('')}
function openRole(name){const r=roleDetails[name];if(!r)return;$('#roleCategory').textContent=roleLibrary.find(x=>x[0]===name)?.[1]||'财会职业方向';$('#roleName').textContent=name;$('#roleSummary').textContent=r.summary;$('#roleDaily').textContent=r.daily;$('#roleHard').innerHTML=r.hard.map(x=>`<li>${x}</li>`).join('');$('#roleSoft').innerHTML=r.soft.map(x=>`<li>${x}</li>`).join('');$('#roleCert').textContent=r.cert;$('#roleEducation').textContent=r.education;$('#rolePath').innerHTML=r.path.map(x=>`<li>${x}</li>`).join('');$('#relatedRoles').innerHTML=r.related.map(x=>`<button data-role="${x}">${x}</button>`).join('');show('roleDetailScreen')}
$('#exploreMoreBtn').onclick=()=>{renderExplorer();show('explorerScreen')};$('#backFromExplorer').onclick=()=>show('finalScreen');$('#backToExplorer').onclick=()=>show('explorerScreen');$('#explorerFilters').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('#explorerFilters button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderExplorer(b.dataset.filter)};$('#explorerGrid').onclick=e=>{const b=e.target.closest('[data-role]');if(b)openRole(b.dataset.role)};$('#relatedRoles').onclick=e=>{const b=e.target.closest('[data-role]');if(b&&roleDetails[b.dataset.role])openRole(b.dataset.role)};
if(document.modelContext?.registerTool)try{document.modelContext.registerTool({name:'start_career_exploration',title:'开始职业探索',description:'根据学生基本情况开始逐个验证三个职业方向。',inputSchema:{type:'object',properties:{grade:{type:'string'},major:{type:'string'},interests:{type:'array',items:{type:'string'}},values:{type:'array',items:{type:'string'}},clarity:{type:'string'}},required:['grade','major','interests','values','clarity'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){state.profile=input;state.interests=input.interests;state.values=input.values;state.careers=choose(input.major,input.interests);state.index=0;state.results=[];renderCareer();show('careerScreen');return{firstDirection:current().name,total:3}}})}catch(e){}

/* V0.6: real portrait recalibration, progressive cases and deeper role guidance */
const portraitDimensions=[['行动验证','研究理解'],['沟通推动','独立深思'],['逻辑证据','体验关怀'],['结构计划','灵活探索']];
function preferenceState(scores,pair){const gap=(scores[pair[0]]||0)-(scores[pair[1]]||0);return{label:Math.abs(gap)<=1?`${pair[0]} / ${pair[1]}（情境型）`:gap>0?pair[0]:pair[1],winner:gap>=0?pair[0]:pair[1],gap}}
function paintPortrait(calibrated=false){const states=portraitDimensions.map(d=>preferenceState(state.profile.scores,d));state.profile.preferences=states.map(x=>x.label);const strong=states.filter(x=>Math.abs(x.gap)>=2).map(x=>x.winner),situational=states.filter(x=>Math.abs(x.gap)<=1).map(x=>x.label.split('（')[0]);$('#portraitTitle').textContent=`${state.profile.major} · ${strong.slice(0,2).join(' × ')||'多情境适应型'}`;$('#portraitIntro').textContent=`${calibrated?'补充回答已参与重新计分。':'根据12道情境题，'}你有${strong.length?strong.join('、'):'多项均衡倾向'}；${situational.length?`在${situational.join('、')}之间会随场景变化。`:'当前倾向较明确。'}这不是能力定论，后续还要用案例验证。`;$('#portraitTags').innerHTML=states.map(x=>`<span>${x.label}</span>`).join('');$('#portraitStrengths').textContent=strong.includes('逻辑证据')?'更容易从事实、标准和数据中形成判断。':strong.includes('体验关怀')?'更容易察觉人的感受、需求和协作影响。':'能够根据任务在人与证据之间切换，但需要用实际案例确认稳定优势。';$('#portraitEnergy').textContent=strong.includes('沟通推动')?'协作、表达并推动结果发生的任务。':strong.includes('独立深思')?'可以独立研究并形成完整观点的任务。':'既需要独立思考、又允许适度交流的任务。';$('#portraitCaution').textContent=situational.length?`你的${situational.join('、')}倾向接近，推荐方向时不会据此做强判断，将重点观察真实任务表现。`:(strong.includes('结构计划')?'继续验证面对变化时的调整能力。':'继续验证长期任务中的节奏与收尾能力。');$('#portraitValues').textContent=state.values.join('、')}
buildPortrait=function(){const answers=preferenceItems.map((_,i)=>$(`input[name=pref${i+1}]:checked`)?.value);if(answers.some(x=>!x))return toast('请完成全部12道情境题');const scores={};answers.forEach(x=>scores[x]=(scores[x]||0)+1);state.profile={grade:$('#grade').value,major:$('#major').value.trim(),interests:[...state.interests],values:[...state.values],clarity:$('input[name=clarity]:checked').value,scores,baseScores:{...scores},startedAt:new Date().toISOString()};state.careers=choose(state.profile.major,state.interests);state.index=0;state.results=[];paintPortrait(false);show('portraitScreen')};
$('#buildPortrait').onclick=buildPortrait;
$('#rebuildPortrait').onclick=()=>{const extra=[1,2,3,4].map(i=>$(`input[name=clarify${i}]:checked`)?.value);if(extra.some(x=>!x))return toast('请完成四道补充问题');const scores={...state.profile.baseScores};const add=k=>scores[k]=(scores[k]||0)+1;extra[0]==='分析与研究'?add('研究理解'):add('沟通推动');extra[1]==='逻辑与细节'?add('逻辑证据'):add('体验关怀');extra[2]==='排斥重复'?add('灵活探索'):add('结构计划');if(extra[3]==='解决难题'){add('研究理解');add('逻辑证据')}else{add('沟通推动');add('行动验证')}state.profile.scores=scores;state.profile.clarifications=extra;paintPortrait(true);show('portraitScreen')};

// Interested students always start with the supported foundation case.
$('#interestedBtn').onclick=()=>{state.mode='guided';prepareTask();show('taskScreen')};
$('#backToCareer').onclick=()=>state.mode==='open'?show('feedbackScreen'):show('careerScreen');

function updateAttempt(result,attempt){const old=state.results.find(x=>x.key===result.key);if(old){old.attempts=old.attempts||[];old.attempts=old.attempts.filter(x=>x.mode!==attempt.mode);old.attempts.push(attempt);Object.assign(old,result)}else setResult({...result,attempts:[attempt]})}
function renderCaseFeedback(ev,answer,feeling,a){const c=current(),positive=/很投入|有一点兴趣/.test(feeling),stage=state.mode==='guided'?'基础案例':'迁移案例';updateAttempt({key:state.careers[state.index],name:c.name,decision:'感兴趣并体验',answer,feeling,score:ev.score,verdict:positive?'值得继续探索':'暂不优先'},{mode:state.mode,score:ev.score,feeling,answer});$('#scoreValue').textContent=ev.score;$('#feedbackStage').textContent=`${stage}反馈`;$('#feedbackTitle').textContent=`「${c.name}」${stage}`;$('#feedbackSummary').textContent=state.mode==='guided'?'你已经完成一次带引导的岗位判断。下面可以查看方法，再决定是否用它解决一个不同背景的问题。':'这次重点不是重复知识点，而是观察你能否把第一题的方法迁移到新业务背景。';$('#choiceResult').textContent=ev.choiceTotal?`${ev.choiceCorrect} / ${ev.choiceTotal} 题正确`:'完成迁移判断';$('#answerResult').textContent=`覆盖 ${ev.keywordHits.length} 个关键视角`;$('#directionVerdict').textContent=positive?'愿意继续了解':'当前兴趣偏低';$('#rubricFeedback').innerHTML=`<h3>你的回答反馈</h3><ul><li>${answer.length>=100?'判断过程较完整，能看到你的分析路径。':'已经形成判断，若补充数据依据和因果关系会更扎实。'}</li><li>${ev.keywordHits.length>=3?'你覆盖了多个岗位视角：'+ev.keywordHits.join('、'):'可对照参考答案补充：'+a.keywords.slice(0,4).join('、')+'。'}</li><li>${state.mode==='open'?'这道题用于检验方法迁移，不要求答案与示例逐字一致。':ev.choiceTotal&&ev.choiceCorrect<ev.choiceTotal?'先理解选择题偏差，再决定是否挑战迁移案例。':'基础判断正确，可以尝试把方法带到新背景。'}</li></ul>`;$('#referenceAnswer').innerHTML=`<p>${a.reference}</p><p><b>评分边界：</b>分数反映本次回答的完整程度，不是职业能力认证。开放回答允许多种合理方案。</p>`;if(state.mode==='guided'){$('#nextAction').textContent='是否用刚学到的方法挑战一个新背景？';$('#actionPurpose').textContent='第二题会更换行业和数据背景，但继续观察同一项核心能力。它用于验证你是否真正理解方法、能否举一反三，而不是把第一题再做一遍。';$('#feedbackChoice').innerHTML='<button class="primary-btn" data-next="transfer">现在继续挑战迁移案例 →</button><button class="outline-btn" data-next="stop">暂时不想继续</button>';$('#continueBtn').hidden=true}else{const r=state.results.find(x=>x.key===state.careers[state.index]),base=r?.attempts?.find(x=>x.mode==='guided');$('#nextAction').textContent='两次案例已形成一组可比较证据';$('#actionPurpose').textContent=`基础案例 ${base?.score??'—'} 分，迁移案例 ${ev.score} 分。${ev.score>=(base?.score||0)?'你在更少引导下保持或提升了完成度，说明方法具有一定迁移性。':'迁移到新背景后完成度下降，建议先理解参考答案，不必据此否定这个方向。'}`;$('#feedbackChoice').innerHTML='';$('#continueBtn').hidden=false;$('#continueBtn').textContent=state.index<state.careers.length-1?'查看下一个候选方向 →':'生成本次探索结论 →'}show('feedbackScreen')}
$('#submitTask').onclick=()=>{const answer=$('#taskAnswer').value.trim(),feeling=$('#taskFeeling').value,a=state.activeAssessment;if(answer.length<40)return toast('请回答案例问题并说明理由，至少写下40个字');if(!feeling)return toast('请选择完成任务时的真实感受');const ev=evaluateAnswer(answer,a);if(ev.error)return toast(ev.error);renderCaseFeedback(ev,answer,feeling,a)};
$('#feedbackChoice').onclick=e=>{const b=e.target.closest('[data-next]');if(!b)return;if(b.dataset.next==='transfer'){state.mode='open';prepareTask();show('taskScreen');return}$('#nextAction').textContent='请选择暂时停止的主要原因';$('#actionPurpose').textContent='原因会帮助区分“对职业没兴趣”和“题目太难或体验方式不合适”，避免一次体验就误判职业。';$('#feedbackChoice').innerHTML='<div class="stop-reasons"><button data-reason="内容不感兴趣">内容不感兴趣</button><button data-reason="题目太难">题目太难</button><button data-reason="题目太简单">题目太简单</button><button data-reason="不喜欢这种体验形式">不喜欢这种体验形式</button><button data-reason="现在没有精力">现在没有精力</button></div>'};
$('#feedbackChoice').addEventListener('click',e=>{const b=e.target.closest('[data-reason]');if(!b)return;const r=state.results.find(x=>x.key===state.careers[state.index]);if(r){r.stopReason=b.dataset.reason;if(b.dataset.reason==='内容不感兴趣')r.verdict='暂不优先'}advance()});

const capabilityDetails={
'核算会计':{hard:[['会计准则与三张报表','理解常见确认、计量与列报规则，知道资产负债表、利润表和现金流量表如何勾稽。例如能解释“有利润但现金不足”的可能原因。'],['账务处理与月末结账','能从原始单据判断科目、制作凭证、核对明细与总账，并按清单完成结账。'],['Excel与财务系统','能使用查找、条件汇总、数据透视表核对数据，并理解ERP中采购到付款、销售到收款的基本链路。']],soft:[['严谨与责任感','金额、期间和科目出现异常时主动复核，不用“差不多”代替证据。'],['业务沟通','能向非财务同事解释缺少什么单据、为什么需要以及如何补齐。']]},
'财务分析':{hard:[['财务报表与经营指标','能拆解收入、成本、利润和现金流，理解指标变化来自销量、价格、结构还是效率。'],['Excel建模与数据处理','能用函数、透视表和图表完成预算实际对比，并保留可复核的数据链路。'],['分析框架','能提出异常、形成假设、补充证据，再给出有边界的经营建议。']],soft:[['业务追问','不止报告数字变化，还会追问业务动作、客户和流程原因。'],['结论表达','先说结论与影响，再展示关键证据，并明确不确定性。']]},
'审计':{hard:[['会计与审计程序','理解主要科目风险，并能选择检查、函证、盘点或分析性复核等程序。'],['审计底稿','能记录目的、样本、证据、结论与复核痕迹，让别人可以重现判断。']],soft:[['职业怀疑','对异常保持追问，但不预设对方有错。'],['高压协作','在截止日期内管理多份材料，及时暴露阻塞而不是最后才反馈。']]},
'税务':{hard:[['主要税种与申报','理解增值税、企业所得税等基本计税逻辑，能核对申报数据与账务。'],['政策检索','能找到有效政策原文，识别适用主体、时间和例外条件。']],soft:[['合规判断','区分可筹划、需核实和不可触碰的事项。'],['持续学习','政策变化后能更新流程并用清楚语言提醒业务。']]},
'资金管理':{hard:[['现金流与资金计划','能根据收付款节奏预测资金缺口并设置安全余额。'],['银行结算与融资基础','理解账户、票据、授信和常见融资资料。']],soft:[['风险意识','优先保障资金安全、授权和时效。'],['协调能力','在业务需求、银行规则和财务制度之间推进解决。']]},
'内控与风险':{hard:[['流程与风险矩阵','能画出关键流程，识别错误、舞弊和合规风险，并对应控制措施。'],['控制测试','能选择样本、检查证据并区分设计缺陷与执行缺陷。']],soft:[['系统思考','看到单点问题背后的流程和责任边界。'],['推动整改','能把风险翻译成业务影响，并跟进责任人与期限。']]},
'财务BP':{hard:[['预算预测与经营分析','能把业务计划转成财务预测，并滚动更新关键假设。'],['业务指标体系','理解收入漏斗、客户、产品和效率指标如何影响利润。']],soft:[['影响决策','不用财务术语压人，而是提供可选择的方案与后果。'],['商业敏感度','能发现数字背后的业务机会与风险。']]},
'ERP实施顾问':{hard:[['财务业务流程','能说明采购、销售、库存和财务之间的数据流与控制点。'],['需求、配置与测试','能把用户需求写成可测试规则，准备数据并记录缺陷。']],soft:[['问题定位','先复现并缩小范围，再判断是数据、配置、权限还是流程问题。'],['客户沟通','面对模糊诉求时确认目标、边界和验收标准。']]},
'商业分析':{hard:[['指标与问题拆解','能把经营问题拆成可计算指标和验证假设。'],['数据分析与呈现','能用Excel/SQL处理数据，用图表说明变化、原因与局限。']],soft:[['结构化思考','把复杂问题拆清优先级和因果链。'],['利益相关方沟通','理解不同部门目标并推动形成共同判断。']]},
'数据分析':{hard:[['SQL与数据清洗','能筛选、关联、分组和检查缺失重复数据，保证口径可复现。'],['统计与可视化','理解描述统计、对照和相关不等于因果，能选择合适图表。']],soft:[['问题定义','先明确业务决策，再决定分析哪些数据。'],['证据边界','主动说明数据限制，不把猜测包装成结论。']]},
'解决方案顾问':{hard:[['需求与方案设计','能梳理客户现状、痛点和约束，把产品能力映射成可落地方案。'],['演示与验证','能设计演示脚本、试点范围和验收标准。']],soft:[['倾听与提问','从客户表述中分辨真正目标和表面需求。'],['跨团队推动','协调销售、产品和交付团队，管理承诺边界。']]},
'企业运营':{hard:[['目标与流程拆解','能把目标拆成指标、动作、负责人和时间节点。'],['数据复盘','能比较计划与结果，定位流程瓶颈并提出下一轮实验。']],soft:[['执行与应变','在变化中抓住关键路径，及时调整资源。'],['协作推动','让多人知道各自交付物和依赖关系。']]}
};
const pathOverrides={
'核算会计':['学好会计基础与Excel','完成一套账务处理模拟','体验财务软件或ERP流程','根据目标决定是否考初级会计','寻找企业财务或事务所实习','用真实经历确认细分方向'],
'财务分析':['理解三张报表与管理会计','掌握Excel分析方法','完成预算差异或经营分析案例','补充SQL或可视化工具','寻找财务分析/经营分析实习','整理作品并复盘能力差距'],
'审计':['建立会计与审计基础','完成底稿、抽样和盘点模拟','体验事务所真实工作节奏','根据长期目标规划CPA','寻找审计或内控实习','用项目证据准备校招'],
'ERP实施顾问':['理解财务与业务流程','体验ERP沙盘或系统课程','完成需求与测试模拟项目','选择一个系统模块深入学习','寻找实施或数字化项目实践','用项目结果验证客户服务意愿']};
function detailSkills(name,type,fallback){const rows=capabilityDetails[name]?.[type];return(rows||fallback.map(x=>[x,`理解这项能力在${name}日常工作中的用途，并能通过案例或项目展示，而不只停留在课程名称。`])).map(x=>`<section><h4>${x[0]}</h4><p>${x[1]}</p></section>`).join('')}
function jdSamples(name,r){const key=(capabilityDetails[name]?.hard||[])[0]?.[0]||r.hard[0];return[{size:'小型企业',title:`${name}助理 / 专员`,text:`协助完成日常业务，熟练使用Excel，能够独立跟进基础事项并保证数据准确。`,signal:'更看重能否尽快上手，职责通常较宽。'},{size:'中型企业',title:`${name}专员`,text:`负责固定模块，按流程输出结果，发现异常并与相关部门沟通，具备${key}基础。`,signal:'更强调流程、协作和稳定交付。'},{size:'大型企业',title:`${name}管培 / 分析岗位`,text:`支持复杂业务或项目，能够形成分析结论并清晰汇报；相关实习、系统工具和项目成果优先。`,signal:'分工更细，通常增加学历、实习或平台要求。'}]}
openRole=function(name){const r=roleDetails[name];if(!r)return;$('#roleCategory').textContent=roleLibrary.find(x=>x[0]===name)?.[1]||'财会职业方向';$('#roleName').textContent=name;$('#roleSummary').textContent=r.summary;$('#roleDaily').textContent=r.daily;$('#roleHard').innerHTML=detailSkills(name,'hard',r.hard);$('#roleSoft').innerHTML=detailSkills(name,'soft',r.soft);$('#roleCert').textContent=r.cert;$('#roleEducation').textContent=r.education;const path=pathOverrides[name]||r.path.map(x=>x.replace(/^大[一二三四]：/,'')).slice(0,5);$('#rolePath').innerHTML=path.map((x,i)=>`<div class="path-step"><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('');const jds=jdSamples(name,r);$('#roleJds').innerHTML=jds.map(x=>`<section><small>${x.size}</small><h4>${x.title}</h4><p>${x.text}</p><em>${x.signal}</em></section>`).join('');$('#roleJdCommon').innerHTML=`<b>三类岗位的共同点</b><p>都在反复验证三件事：相关专业基础、工具与流程能力、把结果准确交付并与他人协作。企业规模越大，通常越重视细分经验、实习证据和表达能力。</p>`;$('#relatedRoles').innerHTML=r.related.map(x=>`<button data-role="${x}">${x}</button>`).join('');show('roleDetailScreen')};

